const SOCKET_DIALOG_ON_EDIT_FIELD = "SOCKET_DIALOG_ON_EDIT_FIELD";
const SOCKET_DIALOG_DISABLE_FIELDS = "SOCKET_DIALOG_DISABLE_FIELDS";
const SOCKET_DIALOG_OPENED = "SOCKET_DIALOG_OPENED";
const SOCKET_DIALOG_CLOSED = "SOCKET_DIALOG_CLOSED";

module.exports = {
  SOCKET_DIALOG_ON_EDIT_FIELD,
  SOCKET_DIALOG_DISABLE_FIELDS,
  SOCKET_DIALOG_OPENED,
  SOCKET_DIALOG_CLOSED,
};
