export const SET_PROMOTIONS_LIST = "SET_PROMOTIONS_LIST";
export const LOAD_NEXT_PROMOTIONS_LIST = "LOAD_NEXT_PROMOTIONS_LIST";
export const LOAD_PREV_PROMOTIONS_LIST = "LOAD_PREV_PROMOTIONS_LIST";
export const ERASE_PROMOTIONS_LIST = "ERASE_PROMOTIONS_LIST";
export const DUPLICATE_PROMOTION = "DUPLICATE_PROMOTION";
export const EDIT_PROMOTION = "EDIT_PROMOTION";
export const DELETE_PROMOTION = "DELETE_PROMOTION";
